### ISSUE TITLE
[Deliverable | Sprint Goal ] I want to be able to send or push tips to my team.

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#1]
**Feature:** I want to be able to send or push tips to my team.
I want to be able to send tips to a list of addresses (a team).
**When** the address have Eth in his wallet, the tips is sent to the contract
**Then** he can Withdraw it later. 
**When** there is no Eth in his wallet
**Then** the tips are sent directly to his wallet.
The sender can decide to send tips directly to the address or he will push directly the tips for all addresses.

### Acceptance criteria 

- [x] Login / Registration
- [x] CRUD Team
- [x] Push / Send tip
- [x] CI/CD pipeline : Dev to Prod

![CNC portal-Page-3 (2)](https://github.com/globe-and-citizen/cnc-portal/assets/28951070/ada5c5cb-c3ec-44df-aff5-095e4deedd2b)

### US1
**As a**: visitor
**I want to**: create an account
**So that i can**: access the platform as a user, interact with the platform. 
**When I do ‘X’ I get ‘Y’**: when i sign in i get a account that can interact with the platform

#### Tasks

- [x] Build the registration feature
    - [x] Build the registration page view
    - [x] Build the registration backend endpoint
    - [x] Integrate the SIWE on the registration page view
- [x] Build the Login Feature
    - [x] Build the login page view
    - [x] Integrate the SIWE on the login page view

### US2

**As a:** User
**I want to**: be able to CRUD my team
**So that i can**: CRUD my team 
**When I do ‘X’ I get ‘Y’**: when i sign in i want to be able to CRUD my team

#### Tasks

- [x] Build the frontend design for CRUD team
    - [x] Create Team Page
    - [x] View Team Page
    - [x] Update team Page
- [x] Build the backend for CRUD
    - [x] Create Team Endpoint
    - [x] Update Team Endpoint
    - [x] User Teams Endpoint
    - [x] User Team Endpoint
    - [x] Delete Team Endpoint

### US3
**As a:** User, a owner of a team
**I want to**: be able to send / Push tips to my team
**So that i can:** Send an equivalent tips to my team members
**When I do ‘X’ I get ‘Y’:** when I push tips I want my team members to receive it in their wallet. When I send tips, I want the tips to be stored in the smart contract.

#### Tasks

- [x] Build the frontend page : Send Tips
- [x] Build the frontend page : Push Tips
- [x] Create Send / Push tips contract
- [x] Integrate Web3 call to Send Tips and push Tips.
