### ISSUE TITLE
[Feature]: Notification system

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#106]
## Description

Create a notification system

- [x] Toast that show the user information an notification
- [x] Notification that show information to user and save them
- [x] Logger that log the information in the console 

**Describe the solution you'd like**
For the moment the toast system have is not efficient. 
We need a good solution and architecture to handle notification and Toast. 

## Acceptance Criteria

- [x] Been Able to call toast in any component. 
- [x] Send a notification From any component
- [x] A user should be able to see notification related to him in his notification page
- [x] And been able to log status anywhere using a logger

```[tasklist]
### Tasks
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/127
- [x] feat: logger formated logger that work only in development mode
```
