### ISSUE TITLE
[CI CD] final version

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#109]
## Description

**Is your feature request related to a problem? Please describe.**

The final version of the CI CD we are looking for
We should be able to have a process that build, run and deploy the app in test, staging, and production.

### Test & Coverage running in the CI CD for

- [x] The backend
- [x] The Frontend
- [x] The contract

### Run The APP in 

- [x] Staging Mod
- [x] Production Mode

### Run The API in 

- [x] Staging Mod
- [x] Production Mode

```[tasklist]
### Tasks
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/118
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/93
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/116
```
