### ISSUE TITLE
[Feature] Bank Smart Contract

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#124]
## Description

**Describe the solution you'd like**
Context: A company (CF, L8) wants to direct his online operation throughout the CNC portal.
Receive Fund From Online Operation
Transfer Fund for Online Operation 
And operate transaction on different Smart Contract

## Acceptance Criteria

- [ ] User Story: Create bank account
- [ ] User Story : Receive fund from online operation 
- [ ] User Story : Pay for a digital service Through CNC portal
- [ ] User Story: Pay an address: Pay employee 
- [ ] User Story: Call external Contract: Send Tips
```[tasklist]
### Tasks
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/119
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/120
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/123
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/126
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/125
```
