### ISSUE TITLE
[Feature] Team Management V2

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#145]
## Description
A Service provider want to be able to manage his team through The CNC portal. 
Create a team,
Add team member
Get notified when a user accept or reject the invitation
And a user should be notified when he got invited to join a team

## Acceptance Criteria

- [x] User Story :  Create a Team
- [x] User Story: Team Member management
- [x] User Story: Team CRUD V2

```[tasklist]
### Tasks
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/146
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/147
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/148
```
