### ISSUE TITLE
[Feature] Form Validation & Form Component

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#250]
## Description

**Is your feature request related to a problem? Please describe.**

We should use system for validating our forms.
We don't have any system to check if our form have valid state so some times our forms validation are not right. 

And in the same time we should try to have a form component that reduce the number of different form component we are creating.

## Ressources
https://formkit.com/essentials/validation
https://ui.nuxt.com/components/form

## Acceptance Criteria

```[tasklist]
### Tasks
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/228
- [x] [Feature] Form Validation sytem
- [ ] [Feature] Form Component
```
