### ISSUE TITLE
[Refactor] Refactor the bank from Upgradable Proxy to Beacon Proxy

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#271]
## Description

Refactor bank Smart contract and use Beacon Proxy

## Acceptance Criteria

- [ ] Make Bank contract upgradable with Beacon Proxy

```[tasklist]
### Tasks
- [ ] https://github.com/globe-and-citizen/cnc-portal/pull/258
- [ ] https://github.com/globe-and-citizen/cnc-portal/issues/248
```
