### ISSUE TITLE
[Feature] Build a Better API

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#284]
## Description

Our API need to be refactor. We need to build a good structure for all the API.

### Avoid having so long controller
![Image](https://github.com/user-attachments/assets/5a95e6f7-0cf2-46e4-9b48-7c9f04564f5a)

We should break it using services

### And make it more structured

--------
Look at this article for more info on how we can design our API.
https://www.freecodecamp.org/news/rest-api-design-best-practices-build-a-rest-api/

Take some and explain what you chose to apply.

## Acceptance Criteria

```[tasklist]
### Tasks
- [ ] New structure with services
- [ ] Add more test
- [ ] Uniformise Response Status
```

**Comment by hermannleboss** [comment]
Delete team is using header instead of URI

![Image](https://github.com/user-attachments/assets/f1bd9f70-bf71-44cc-bd30-32ef94736377)
