### ISSUE TITLE
[Sliver] As a visitor, I would like to be able to create an account or log in if I already have one.

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#4]
**As a**: visitor
**I want to**: create an account
**So that i can**: access the platform as a user, interact with the platform. 
**When I do ‘X’ I get ‘Y’**: when i sign in i get a account that can interact with the platform

![CNC portal-Page-3 (4)](https://github.com/globe-and-citizen/cnc-portal/assets/28951070/88110148-3ba6-4c19-aef7-8731ed0c5d8c)

#### Stack :

- SIWE
- NodeJs
- Prisma
- PostgresQL
- VueJs
- Tailwind
- DaisyUI

#### Tasks

- [x] Build the registration feature
    - [x] Build the registration page view
    - [x] Build the registration backend endpoint
    - [x] Integrate the SIWE on the registration page view
- [x] Build the Login Feature
    - [x] Build the login page view
    - [x] Integrate the SIWE on the login page view
