### ISSUE TITLE
feat: create contract events page

### ISSUE THREAD

**Issue by farrellh1** [globe-and-citizen/cnc-portal#49]
create new section in drawer called `transaction` in that page it should show all the events from the contract

```[tasklist]
### Tasks
- [x] Create new section
- [x] Create transaction view
- [x] Fetch all events from the contract
```
