### ISSUE TITLE
[Sliver] As a user i should be able to CRUD my team

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#5]
**As a:** User
**I want to**: be able to CRUD my team
**So that i can**: CRUD my team 
**When I do ‘X’ I get ‘Y’**: when i sign in i want to be able to CRUD my team

![CNC portal-Page-3 (5)](https://github.com/globe-and-citizen/cnc-portal/assets/28951070/c27ceb2d-913b-4ec5-bf32-e4fa898f61da)

#### Stack : 

- NodeJs
- VueJs
- Prisma
- PostgresQL
- Tailwind
- DaisyUI

#### Tasks

- [x] Build the frontend design for CRUD team
    - [x] Create Team Page
    - [x] View Team Page
    - [x] Update team Page
- [x] Build the backend for CRUD
    - [x] Create Team Endpoint
    - [x] Update Team Endpoint
    - [x] User Teams Endpoint
    - [x] User Team Endpoint
    - [x] Delete Team Endpoint
