### ISSUE TITLE
[Sliver] As a team owner i can send or push tips to my team

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#6]
**As a:** User, a owner of a team
**I want to**: be able to send / Push tips to my team
**So that i can:** Send an equivalent tips to my team members
**When I do ‘X’ I get ‘Y’:** when I push tips I want my team members to receive it in their wallet. When I send tips, I want the tips to be stored in the smart contract.

![CNC portal-Page-3](https://github.com/globe-and-citizen/cnc-portal/assets/28951070/1699e14e-7aad-412b-9a7e-b051fa3f3325)

#### Stack : 

- NodeJs
- VueJs
- Prisma
- PostgresQL
- Tailwind
- DaisyUI
- EtherJs
- SOLIDITY

#### Tasks

- [x] Build the frontend page : Send Tips
- [x] Build the frontend page : Push Tips
- [x] Create Send / Push tips contract
- [x] Integrate Web3 call to Send Tips and push Tips.
